/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbyan' at '1/23/18 3:14 PM' with Gradle 2.13
 *
 * @author sbyan, @date 1/23/18 3:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
